Updates the release workflow to support python 3.11 and MacOS arm64.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ['3.8', '3.9', '3.10', 'pypy-3.8']
+        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy-3.8']
     steps:
       - uses: actions/checkout@v3
       - name: Set up python
@@ -20,68 +20,69 @@ jobs:
 
       - name: Create a virtual environment
         run: git submodule init && git submodule update && python3 -m venv ./venv && . venv/bin/activate
+      - run: pip install --upgrade setuptools
       - run: pip install -r requirements.txt
       - run: pip install -e .
       - run: py.test
 
-  source-distribution:
-    if: startsWith(github.ref, 'refs/tags/')
-    name: Source distribution
-    runs-on: ubuntu-latest
-    needs: [test]
-    strategy:
-      matrix:
-        python-version: [ '3.10' ]
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Build sdist
-        run: python3 setup.py sdist
-
-      - name: Upload source to Github
-        uses: actions/upload-artifact@v2
-        with:
-          name: source
-          path: ./dist/amazon.ion-*.tar.gz
-
-      - uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-skip-session-tagging: true
-          aws-region: us-west-2
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
-          role-duration-seconds: 900
-
-      - name: Upload source to s3
-        run: |
-          zip ion-python-source ./dist/amazon.ion-*.tar.gz
-          aws s3 mv ion-python-source.zip ${{ secrets.AWS_SOURCE_BUCKET_URL }} --acl bucket-owner-full-control
-
-      - name: Install the released source from PYPI
-        run: |
-          sleep 300s
-
-          for (( i=0; i<3; i++ ))
-          do
-            v=""
-
-            if ! (pip install --no-binary :all: amazon.ion==${GITHUB_REF##*/v}) then
-              echo "Unable to install the desired version"
-              sleep 120s
-              continue
-            fi
-
-            v=$( pip show amazon.ion | grep Version )
-            break
-          done
-
-          if [[ $v != "Version: ${GITHUB_REF##*/v}" ]]
-          then
-            echo "Exiting because unable to install the new version from PYPI"
-            exit 1
-          fi
+#  source-distribution:
+#    if: startsWith(github.ref, 'refs/tags/')
+#    name: Source distribution
+#    runs-on: ubuntu-latest
+#    needs: [test]
+#    strategy:
+#      matrix:
+#        python-version: [ '3.10' ]
+#    steps:
+#      - uses: actions/checkout@v3
+#
+#      - name: Build sdist
+#        run: python3 setup.py sdist
+#
+#      - name: Upload source to Github
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: source
+#          path: ./dist/amazon.ion-*.tar.gz
+#
+#      - uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          role-skip-session-tagging: true
+#          aws-region: us-west-2
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
+#          role-duration-seconds: 900
+#
+#      - name: Upload source to s3
+#        run: |
+#          zip ion-python-source ./dist/amazon.ion-*.tar.gz
+#          aws s3 mv ion-python-source.zip ${{ secrets.AWS_SOURCE_BUCKET_URL }} --acl bucket-owner-full-control
+#
+#      - name: Install the released source from PYPI
+#        run: |
+#          sleep 300s
+#
+#          for (( i=0; i<3; i++ ))
+#          do
+#            v=""
+#
+#            if ! (pip install --no-binary :all: amazon.ion==${GITHUB_REF##*/v}) then
+#              echo "Unable to install the desired version"
+#              sleep 120s
+#              continue
+#            fi
+#
+#            v=$( pip show amazon.ion | grep Version )
+#            break
+#          done
+#
+#          if [[ $v != "Version: ${GITHUB_REF##*/v}" ]]
+#          then
+#            echo "Exiting because unable to install the new version from PYPI"
+#            exit 1
+#          fi
 
   build-wheels:
     name: Build wheels on ${{ matrix.os }}
@@ -91,10 +92,25 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        python-version: [ '3.10']
-        os: [macos-latest, windows-latest, ubuntu-latest]
+        include:
+          - os: macos-latest
+            arch: x86_64
+            cibw_arch: "x86_64"
+          - os: macos-14  # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
+            arch: arm64
+            cibw_arch: "arm64"
+          - os: windows-latest
+            cibw_arch: "auto"
+          - os: ubuntu-latest
+            cibw_arch: "auto aarch64"
+
     steps:
       - uses: actions/checkout@v3
+
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
 
       - name: Set up pip and setuptools
         run: |
@@ -108,15 +124,13 @@ jobs:
           platforms: all
 
       - name: Install cibuildwheel
-        run: python3 -m pip install cibuildwheel==2.4.0
+        run: python3 -m pip install cibuildwheel==2.16.5
 
       - name: Build wheels
         run: python3 -m cibuildwheel --output-dir wheelhouse
         env:
-          CIBW_SKIP: "pp* *-win32"
-          CIBW_ARCHS_WINDOWS: "auto"
-          CIBW_ARCHS_LINUX: "auto aarch64"
-          CIBW_ARCHS_MACOS: "x86_64"
+          CIBW_SKIP: "pp* *-win32 cp36-* cp37-* cp38-*"
+          CIBW_ARCHS: ${{ matrix.cibw_arch }}
 
       - name: Upload wheels to Github
         uses: actions/upload-artifact@v2
@@ -124,50 +138,50 @@ jobs:
           name: wheels
           path: ./wheelhouse/*.whl
 
-  upload-wheels:
-    name: Upload wheels to S3
-    runs-on: [ubuntu-latest]
-    needs: [build-wheels]
-    steps:
-      - uses: actions/download-artifact@v2
-        with:
-          name: wheels
-
-      - uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-skip-session-tagging: true
-          aws-region: us-west-2
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
-          role-duration-seconds: 900
-
-      - name: Upload wheels to s3
-        run: |
-          zip ion-python-wheels ./*.whl
-          aws s3 mv ion-python-wheels.zip ${{ secrets.AWS_WHEELS_BUCKET_URL }} --acl bucket-owner-full-control
-
-      - name: Install the released wheels from PYPI
-        run: |
-          sleep 300s
-
-          for (( i=0; i<3; i++ ))
-          do
-            v=""
-
-            if ! (pip install --only-binary :all: amazon.ion==${GITHUB_REF##*/v}) then
-              echo "Unable to install the desired version"
-              sleep 120s
-              continue
-            fi
-
-            v=$( pip show amazon.ion | grep Version )
-            break
-          done
-
-          if [[ $v != "Version: ${GITHUB_REF##*/v}" ]]
-          then
-            echo "Exiting because unable to install the new version from PYPI"
-            exit 1
-          fi
+#  upload-wheels:
+#    name: Upload wheels to S3
+#    runs-on: [ubuntu-latest]
+#    needs: [build-wheels]
+#    steps:
+#      - uses: actions/download-artifact@v2
+#        with:
+#          name: wheels
+#
+#      - uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          role-skip-session-tagging: true
+#          aws-region: us-west-2
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
+#          role-duration-seconds: 900
+#
+#      - name: Upload wheels to s3
+#        run: |
+#          zip ion-python-wheels ./*.whl
+#          aws s3 mv ion-python-wheels.zip ${{ secrets.AWS_WHEELS_BUCKET_URL }} --acl bucket-owner-full-control
+#
+#      - name: Install the released wheels from PYPI
+#        run: |
+#          sleep 300s
+#
+#          for (( i=0; i<3; i++ ))
+#          do
+#            v=""
+#
+#            if ! (pip install --only-binary :all: amazon.ion==${GITHUB_REF##*/v}) then
+#              echo "Unable to install the desired version"
+#              sleep 120s
+#              continue
+#            fi
+#
+#            v=$( pip show amazon.ion | grep Version )
+#            break
+#          done
+#
+#          if [[ $v != "Version: ${GITHUB_REF##*/v}" ]]
+#          then
+#            echo "Exiting because unable to install the new version from PYPI"
+#            exit 1
+#          fi
